version: '3.8'

services:
  pinode-telegram-bot:
    build: .
    container_name: pinode-telegram-solohost
    restart: always
    environment:
      - NODE_ENV=production
      - PROBE_HOST=host.docker.internal
      - STELLAR_CORE_URL=http://host.docker.internal:11626
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./data:/app/data
    network_mode: "host"
